### ISSUE TITLE
    import bleu_scorer** **ModuleNotFoundError: No module named 'bleu_scorer 

### ISSUE THREAD

**Issue by foreseez** [Evan-Gao/conversational-QG#1]
zengyj@id-d3:~/conversational-QG/conversational-QG/scripts$ bash generate.sh
[2019-09-27 11:55:47,954 INFO] 8360 Example before filter
[2019-09-27 11:55:47,957 INFO] 8360 Example after filter
  0%|                                                                                                                                                                                     | 0/4180 [00:00<?, ?it/s]/usr/local/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
/home/zengyj/conversational-QG/conversational-QG/code/onmt/translate/translator.py:520: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(a, requires_grad=False)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4180/4180 [11:56<00:00,  5.83it/s]
Traceback (most recent call last):
  File "/home/zengyj/conversational-QG/conversational-QG/code/tools/eval/eval.py", line 3, in **<module>
    from bleu.bleu import Bleu
  **File "/home/zengyj/conversational-QG/conversational-QG/code/tools/eval/bleu/bleu.py", line 14, in <module>
    import bleu_scorer**
**ModuleNotFoundError: No module named 'bleu_scorer'****
zengyj@id-d3:~/conversational-QG/conversational-QG/scripts$

----------------上面是报错的信息

import os,sys
sys.path.append("..")
sys.path.append(os.getcwd())

import bleu_scorer
from bleu.bleu_scorer import BleuScorer

我在 bleu.py里面已经了如上的代码 还是不能导入同级目录的代码呢 
 
![image](https://user-images.githubusercontent.com/18757695/65746145-979f7380-e130-11e9-80cc-7273bcf78541.png)

![image](https://user-images.githubusercontent.com/18757695/65746161-a4bc6280-e130-11e9-8c86-6db9cd1aa9a6.png)

这个明明在一级目录呢

是什么问题，求解答

**Comment by foreseez** [comment]
这两个bleu.py 和bleu_scorer.py  是几年前的老代码  py2.7的  一运行 `bash scripts/generate.sh`
就出错   也不知道大佬是怎么跑通的

**Comment by foreseez** [comment]
![image](https://user-images.githubusercontent.com/18757695/65770990-d3a2fa80-e169-11e9-980a-c6d247a0c305.png)



这一部分的老代码 有错误   作者当时怎么跑通的 呢

**Comment by foreseez** [comment]
:~/conversational-QG/conversational-QG/scripts$ bash generate.sh
[2019-09-27 21:04:01,482 INFO] 8360 Example before filter
[2019-09-27 21:04:01,484 INFO] 8360 Example after filter
  0%|                                                                                                                                                                                     | 0/4180 [00:00<?, ?it/s]/usr/local/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
/home/zengyj/conversational-QG/conversational-QG/code/onmt/translate/translator.py:520: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(a, requires_grad=False)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4180/4180 [11:45<00:00,  5.92it/s]
scores:

Traceback (most recent call last):
  File "/home/zengyj/conversational-QG/conversational-QG/code/tools/eval/eval.py", line 79, in <module>
    eval(args.out_file, args.tgt_file)
  File "/home/zengyj/conversational-QG/conversational-QG/code/tools/eval/eval.py", line 70, in eval
    return eval.evaluate()
  File "/home/zengyj/conversational-QG/conversational-QG/code/tools/eval/eval.py", line 31, in evaluate
    score, scores = scorer.compute_score(self.gts, self.res)
  File "/home/zengyj/conversational-QG/conversational-QG/code/tools/eval/bleu/bleu.py", line 40, in compute_score
    bleu_scorer += (hypo[0], ref)
  File "/home/zengyj/conversational-QG/conversational-QG/code/tools/eval/bleu/bleu_scorer.py", line 166, in __iadd__
    self.cook_append(other[0], other[1])
  File "/home/zengyj/conversational-QG/conversational-QG/code/tools/eval/bleu/bleu_scorer.py", line 115, in cook_append
    **cooked_test = cook_test(test, self.crefs[-1])
TypeError: cook_test() missing 1 required positional argument: 'refmaxcounts'**

**Comment by Yifan-Gao** [comment]
在/path/to/conversational-QG下面跑 ./scripts/generate.sh 
这是我的结果
![image](https://user-images.githubusercontent.com/23121591/65876442-ce3cee80-e3bb-11e9-9542-1031a5881362.png)

另外translate.py用python3.6；eval.py用python2.7

你试试看行不行
