### ISSUE TITLE
How to run different models that used in your paper for ablation study?

### ISSUE THREAD

**Issue by AlbertChen1991** [Evan-Gao/conversational-QG#3]
Does the model with CorefGenerator in your code denote the CFNet model in your paper? And the model with CopyGenerator denote MSNet? I tried to disable the coref_vocab and coref_attn commands to run the base model, but a ZeroDivisionError occurs.

**Comment by Yifan-Gao** [comment]
No, currently the released implementation only supports CFNet.

**Comment by AlbertChen1991** [comment]
I just want to test the performance of the base model and estimate how mach the Coreference Alignment and Conversation Flow Modeling will improve upon the base model. Would you release the code of MSNet?

**Comment by Yifan-Gao** [comment]
Thanks for your interest. But currently I do not have the bandwidth to clean up the baseline code and release. I may do it in the future.
You can also try to implement the baseline by yourself. There is little difference between baseline model and pointer-generator.
