### ISSUE TITLE
Could give more explanation about the preprocess data or maybe the code about the preprocess data?

### ISSUE THREAD

**Issue by kugwzk** [Evan-Gao/conversational-QG#4]
Hello, @Evan-Gao, I am very interesting about your work CQG, but I notice that your code in data is preprocessed, so I don't know how to split the original CoQA data. Could you explain more detail about the data format or give the original code about that? THX~

**Comment by Yifan-Gao** [comment]
Hi, the id in released data is same as id in CoQA. The preprocessed code requires several dependencies so I do not plan to release it.
