### ISSUE TITLE
About the train hyper-parameters

### ISSUE THREAD

**Issue by kugwzk** [Evan-Gao/conversational-QG#5]
Hi, @Evan-Gao . Thanks for the interesting work. When I trained a model use your code I got a result `B1=36.86, B2=22.32, B3=15.77, R-L=46.37`, I found that the result is below the pretrain model you given or the paper's report. So could you give some details about the train procedure？

**Comment by Yifan-Gao** [comment]
The model is end-to-end trained with scripts/train.sh. I think the difference comes from environment setup. Perhaps I will consider releasing a dockerlized environment in future but I do not have time to do it currently.

**Comment by kugwzk** [comment]
Thanks a lot.

**Comment by kugwzk** [comment]
Maybe you can give a Rouge parameters?

**Comment by Yifan-Gao** [comment]
What do you mean by Rouge parameters? you mean the rouge score? of what?

**Comment by kugwzk** [comment]
Sorry, I saw your eval.py, you don't use the rouge perl script. I mistook about that, because Lin's original Rouge Perl script use some parameters such as `-n 2 -x -m -2 4 -u -c 95 -r 1000 -f A -p 0.5 -t 0 -l 250` to eval. Sorry...
