### ISSUE TITLE
How to generate the question from custom test data? 

### ISSUE THREAD

**Issue by bhavikapanara** [Evan-Gao/conversational-QG#7]
Hi,

Thanks @Yifan-Gao sharing the code. It is a great job.

But, the question is how to generate the question from a custom text of the paragraph. Actually, you have directly provided the processed train and test data.

So, I am not able to use my custom test data in the model that needs to be processed.

Kindly request you to can you please provide function so that I can feed processed custom test data to model?

Thanks a lot,
Bhavika

**Comment by Yifan-Gao** [comment]
Thanks for your interest. The data is processed under a similar format as OpenNMT (https://github.com/OpenNMT/OpenNMT-py). We also use neuralcoref from https://github.com/huggingface/neuralcoref to annotate the coreference in conversations.

**Comment by bhavikapanara** [comment]
Thanks, @Yifan-Gao 

> Thanks for your interest. The data is processed under a similar format as OpenNMT (https://github.com/OpenNMT/OpenNMT-py). We also use neuralcoref from https://github.com/huggingface/neuralcoref to annotate the coreference in conversations.

**Comment by bhavikapanara** [comment]
> Thanks for your interest. The data is processed under a similar format as OpenNMT (https://github.com/OpenNMT/OpenNMT-py). We also use neuralcoref from https://github.com/huggingface/neuralcoref to annotate the coreference in conversations.

I have checked OpenNMT. However, I didn't get any success. 
Actually I want to generate the question from custom feeding text data using your command `scripts/generate.sh`. 

To run this command, I need to feed processed data of a custom test sample like `coqg-test-3.json` that you have already set as default in `generate.sh->translate.py` file.

So, just want to replace `coqg-test-3.json`  to `coqg-custom_test-3.json` file in translate.py.
 
So, please kindly request you to help me to get the `cong-custom_test-3.json` file for the custom text sample.

Thank you

**Comment by Yifan-Gao** [comment]
Yes, in order to use custom data for generation, you need to prepare the dataset similar to OpenNMT format. More specifically, the input paragraph ('src' in `coqg-test-3.json`) is in the format of `[token, answer_embedding_feature, chunk_emb, turn_emb]`, and the multi-turn dialog history is in the format of `[<q> q1 <a> a1, [<q> q2 <a> a2] ...`

**Comment by zhoudoufu** [comment]
Hi @Yifan-Gao,
Thanks for your explanation above, but there is some points still unclear for me. 
Correct me if I made any misunderstanding here,
I saw ANS_O, ANS_B, ANS_I tags for this field answer_embedding_feature in your coqg-test-3.json file. It should be some kind of attention result of the question to pose in the src text. 
1, Before you posing questions, how do you determine which place to mark as ANS_B, ANS_O? 
2, May be I skip something from your paper (My bad), How do you generate the first QA for an unseen text? Cause I saw all data examples starts from TURN 2.
THX, 
Zhou

**Comment by Yifan-Gao** [comment]
Hi @zhoudoufu, thanks for your interest.

>1, Before you posing questions, how do you determine which place to mark as ANS_B, ANS_O?

To establish concrete evaluation between our model and baselines, we assume the answers are known before generation. See Section 4.2 Locating Extractive Answer Spans. for more details. 

>2, May be I skip something from your paper (My bad), How do you generate the first QA for an unseen text? Cause I saw all data examples starts from TURN 2.

To better evaluate the model's capability of generating `conversational` questions, our task requires there always exists a conversation history. Therefore, we only consider generation starting from the second turn.
